version: 0.1.0-{build}
configuration:
- Release
platform:
- AnyCPU
os: Windows Server 2012 R2
build:
  project: DokanNFC.sln
  verbosity: minimal
notifications:
- provider: Email
  to:
  - reports@islog.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true